ALTER TABLE agent_notification_preferences
    ADD COLUMN IF NOT EXISTS max_concurrent_tasks INTEGER NOT NULL DEFAULT 2,
    ADD COLUMN IF NOT EXISTS max_queued_tasks INTEGER NOT NULL DEFAULT 20,
    ADD COLUMN IF NOT EXISTS auto_recovery_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS quality_handoff_threshold DOUBLE PRECISION NOT NULL DEFAULT 0.65,
    ADD COLUMN IF NOT EXISTS handoff_on_failure BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS handoff_on_permission BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS handoff_on_budget BOOLEAN NOT NULL DEFAULT TRUE;
